import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="flex flex-col bg-[#0F172B] min-h-screen w-full">
        <Header />
        <div className="min-h-[calc(100vh-104px)]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
